---
name: Test

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          fail_ci_if_error: true
